Document: greyfix
Title: Debian greyfix Manual
Author: <insert document author here>
Abstract: This manual describes what greyfix is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/greyfix/greyfix.sgml.gz

Format: postscript
Files: /usr/share/doc/greyfix/greyfix.ps.gz

Format: text
Files: /usr/share/doc/greyfix/greyfix.text.gz

Format: HTML
Index: /usr/share/doc/greyfix/html/index.html
Files: /usr/share/doc/greyfix/html/*.html

  
